#!/bin/zsh

if [[ $# -lt 2 ]]; then
  echo "No arguments supplied"
  echo "Usage: $0 token branch [ commit ]"
  exit 2;
fi

API=https://percy.io/api/v1 # http://dev.percy.local:9090/api/v1
TOKEN=$1
BRANCH=$2

shift 2
PERCY_API=$API PERCY_TOKEN=$TOKEN PERCY_BRANCH=$BRANCH PERCY_TARGET_BRANCH=$BRANCH npm run snapshots $@

# COMMIT=$3
# shift 3
# PERCY_API=$API PERCY_TOKEN=$TOKEN PERCY_BRANCH=$BRANCH PERCY_TARGET_BRANCH=$BRANCH PERCY_TARGET_COMMIT=$COMMIT npm run snapshots $@
